add-symbol-file build/add
add-symbol-file build/affinity
add-symbol-file build/barrier
add-symbol-file build/bootblock
add-symbol-file build/condition
add-symbol-file build/consumer
add-symbol-file build/mbox_server
add-symbol-file build/mbox_client
add-symbol-file build/multicore
add-symbol-file build/producer
add-symbol-file build/ready_to_exit
add-symbol-file build/shell
add-symbol-file build/test_affinity
add-symbol-file build/test_barrier
add-symbol-file build/wait_locks
add-symbol-file build/waitpid