add-symbol-file build/print1
add-symbol-file build/print2
add-symbol-file build/fly
add-symbol-file build/lock1
add-symbol-file build/lock2
add-symbol-file build/timer
add-symbol-file build/sleep
add-symbol-file build/fly1
add-symbol-file build/fly2
add-symbol-file build/fly3
add-symbol-file build/fly4
add-symbol-file build/fly5